// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVZWfhch9bYc0LET7L6FiTauI7LtE3jw',
    appId: '1:445237666877:web:309f37911391bfd9fd7654',
    messagingSenderId: '445237666877',
    projectId: 'mossis-family',
    authDomain: 'mossis-family.firebaseapp.com',
    storageBucket: 'mossis-family.appspot.com',
    measurementId: 'G-PWCGH9XXTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxCL-B0kj68pzzwpjsDexSW6wFMoQK4I',
    appId: '1:445237666877:android:31ed266985da1aadfd7654',
    messagingSenderId: '445237666877',
    projectId: 'mossis-family',
    storageBucket: 'mossis-family.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbB-ubSmZO26IbpBMKJxuw00MBLUv2Myw',
    appId: '1:445237666877:ios:a0aaac7ad92a2b6dfd7654',
    messagingSenderId: '445237666877',
    projectId: 'mossis-family',
    storageBucket: 'mossis-family.appspot.com',
    iosBundleId: 'com.example.clossB1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbB-ubSmZO26IbpBMKJxuw00MBLUv2Myw',
    appId: '1:445237666877:ios:f9b91fcd1eb00c64fd7654',
    messagingSenderId: '445237666877',
    projectId: 'mossis-family',
    storageBucket: 'mossis-family.appspot.com',
    iosBundleId: 'com.example.clossB1.RunnerTests',
  );
}
